### ISSUE TITLE
Problems with pedigree

### ISSUE THREAD

**Issue by thoree** [gdorum/relMix#15]
Hi
I updated relMixfrom github earlier today. I can't manage to run relMixGUI() with pedigrees. I keep getting the error message
Error in relMix(pedigrees$H1, locus, R = R[[i]], datamatrix1, ids = idxC1,  : 
  Argument pedigrees should be a list of Familias pedigrees

Do you have an example with pedigrees that works with `relMixGUI()`? It works in raw R with `relMix()`.
Sorry for not being able to provide a more specific example.

**Comment by gdorum** [comment]
Hi,
In the testdata/valid folder you can find working examples. The files "custom_pedigree_maternity_duo.R" and "custom_pedigree_unrelated_duo.R" show examples of custom pedigrees that can be provided to relMixGUI().

**Comment by thoree** [comment]
Your example works nicely - thank you so much!

**Comment by gdorum** [comment]
This issue has now been fixed. There was a bug causing an error only when there were custom pedigrees and different contributors under H1 and H2.

**Comment by thoree** [comment]
This now works wonderfully! Using `relMixGUI()` I get the answer in seconds. My, probably poor, implementation in raw R using relMix() took much longer.
Thanks!
